defaults:
  - ppo_megatron_trainer
  - _self_

actor_rollout_ref:
  actor:
    policy_loss:
      loss_mode: sdpo
    self_distillation:
      full_logit_distillation: true
      distillation_topk: 100
      alpha: 0.5
      success_reward_threshold: 1.0
      teacher_regularization: ema
      teacher_update_rate: 0.01
      dont_reprompt_on_self_success: true
      remove_thinking_from_demonstration: false
      include_environment_feedback: false
      environment_feedback_only_without_solution: false
      max_reprompt_len: 16384
      reprompt_truncation: right
      is_clip: 2.0
  rollout:
    calculate_log_probs: true

algorithm:
  adv_estimator: grpo
  rollout_correction:
    rollout_is: token
    rollout_is_threshold: 2.0

trainer:
  critic_warmup: 0
